- name: deploy static 
  gather_facts: false
  hosts: '{{ host }}'
  remote_user: root
  vars:
    src_dir: '{{ src_dir }}'
    dest_dir: '{{ dest_dir }}'

  tasks:
  #####判断相关的目录是否存在,不存在则创建
    - name: create directory if don't exist
      block:
      - name: "Checking directory"
        stat:
          path: "{{item}}"
        with_items:
          - ["/use/share/nginx/{{ dest_dir }}"]
        register: folder_stats
            
      - name: "creat multiple directory"
        file:
          path: "{{item.item}}"
          state: directory
          mode: 0755
          group: root
          owner: root
        with_items:
         - "{{folder_stats.results}}"
        when: item.stat.exists == false
  ####同步静态文件
    - name: sync file
      synchronize: 
        src: "{{item}}"
        dest: /usr/share/nginx/{{ dest_dir }}
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.idea"
          - "--exclude=.gitignore"
      with_items:
        - ["{{ src_dir }}"]
#      notify:
#       - "reload Nginx"
  ####重启nginx服务

#  handlers:
#    - name: "reload Nginx"

#      service: name=nginx state=reloaded
